### ISSUE TITLE
HTTPステータスコードのうち100番台を成功とみなすのは無理があるのではないか

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/SkyStory#1]
https://github.com/SigureRuri/SkyStory/blob/acd3c2d974581ac4462b403e0eef23efe354f554/src/main/kotlin/com/github/shur/skystory/HttpResponse.kt#L25-L30

cf. https://developer.mozilla.org/ja/docs/Web/HTTP/Status

**Comment by SigureRuri** [comment]
修正しました。ありがとうございます。
