### ISSUE TITLE
ステータスコードの指定が不十分

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/SkyStory#2]
https://github.com/SigureRuri/SkyStory/blob/7d7e8350048219b457aa306fb9f33c799da6ed53/src/main/kotlin/com/github/shur/skystory/HttpResponse.kt#L30
`||`でつないであるので、200以上と400未満のいずれか一方を満たすだけでtrueが返りませんか？

**Comment by SigureRuri** [comment]
返信が遅くなり申し訳ないです。
報告ありがとうございます。
ミスです！
至急修正します。
